spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springCloudAlibaba-nacos-client
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
com:
  kdy:
   name: 我是康哥
server:
  port: 8080