spring:
  datasource:
    url: jdbc:mysql://bj-cdb-9dmydd1c.sql.tencentcdb.com:20584/customer?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ###
    password: ###
    driver-class-name: com.mysql.jdbc.Driver
