spring:
  datasource:
    url: jdbc:mysql://bj-cdb-9dmydd1c.sql.tencentcdb.com:XXx/order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: XXx
    password: XXx
    driver-class-name: com.mysql.jdbc.Driver