spring:
  profiles:
    active: dev
  application:
      name: order-discovery
  cloud:
    nacos:
      discovery:
        service: order-provider
      #取消Sentinel控制台懒加载
    sentinel:
      eager: true
server:
    port: 8081
    servlet:
      context-path: /order
mybatis:
  configuration:
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

