spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    # 腾讯云 centos@123A  本机 123456
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #服务的名称，会展示在nacos服务列表，要求唯一，可以不写，默认是spring.application.name的值
        username: nacos
        password: 123@#nacos